def display_banner():
    print("\033[1;35m")
    print("****************************************************************")
    print("*    __          __             _                              *")
    print("*    \\ \\        / /__ _ __ ___ | |__   ___ _ __ ___ ___        *")
    print("*     \\ \\ /\\ / / / _ \\ '__/ _ \\| '_ \\ / _ \\ '__/ __/ _ \\       *")
    print("*      \\ V  V / /  __/ | | (_) | |_) |  __/ | | (_|  __/       *")
    print("*       \\_/\\_/  \\___|_|  \\___/|_.__/ \\___|_|  \\___\\___|       *")
    print("*                                                              *")
    print("****************************************************************")
    print("\033[1;36m")
    print("                 Vulnerability Scanner v2.0")
    print("\033[1;33m")
    print("                 Developed by: Nitish Sharma")
    print("\033[1;32m")
    print("          Support: https://t.me/supportBlackEnthembot")
    print("         	    Instagram: @nitishraj2645")
    print("\033[1;35m")
    print("################################################################")
    print("\033[0m")
